//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public admin()
        {
            this.RS_Menu = new HashSet<RS_Menu>();
            this.RS_Menu1 = new HashSet<RS_Menu>();
            this.RS_Branch = new HashSet<RS_Branch>();
            this.RS_Branch1 = new HashSet<RS_Branch>();
        }
    
        public int admin_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> admin_type { get; set; }
        public Nullable<int> status_id { get; set; }
        public string admincodereg { get; set; }
        public string description { get; set; }
    
        public virtual status status { get; set; }
        public virtual ICollection<RS_Menu> RS_Menu { get; set; }
        public virtual ICollection<RS_Menu> RS_Menu1 { get; set; }
        public virtual ICollection<RS_Branch> RS_Branch { get; set; }
        public virtual ICollection<RS_Branch> RS_Branch1 { get; set; }
    }
}
