//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANhatKyHeThong
    {
        public int ThongTin_ID { get; set; }
        public string NguoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string ChucNang { get; set; }
        public string HanhDong { get; set; }
        public string DoiTuong { get; set; }
        public string NoiDung { get; set; }
    }
}
