//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public long AssignmentId { get; set; }
        public long LocationId { get; set; }
        public string AssignmentNote { get; set; }
        public System.DateTime AssignmentStart { get; set; }
        public System.DateTime AssignmentEnd { get; set; }
        public System.DateTime AssignmentPriority { get; set; }
    }
}
