//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhMuc
    {
        public long HangHoaID { get; set; }
        public int NVLID { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    
        public virtual DMHangHoa DMHangHoa { get; set; }
        public virtual DMNVL DMNVL { get; set; }
    }
}
