//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMBan
    {
        public DMBan()
        {
            this.HoaDon_Ban = new HashSet<HoaDon_Ban>();
        }
    
        public int BanID { get; set; }
        public string MaBan { get; set; }
        public string TenBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> LoaiBan { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<HoaDon_Ban> HoaDon_Ban { get; set; }
    }
}
