//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMDonViTinh
    {
        public DMDonViTinh()
        {
            this.DMNVLs = new HashSet<DMNVL>();
            this.DMNVLs1 = new HashSet<DMNVL>();
            this.DMNVLs2 = new HashSet<DMNVL>();
            this.DMNVLs3 = new HashSet<DMNVL>();
        }
    
        public int DonViTinhID { get; set; }
        public string TenDonViTinh { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<DMNVL> DMNVLs { get; set; }
        public virtual ICollection<DMNVL> DMNVLs1 { get; set; }
        public virtual ICollection<DMNVL> DMNVLs2 { get; set; }
        public virtual ICollection<DMNVL> DMNVLs3 { get; set; }
    }
}
