//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMNhanVien
    {
        public DMNhanVien()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.HoaDons1 = new HashSet<HoaDon>();
            this.PhanCongs = new HashSet<PhanCong>();
            this.PhieuChis = new HashSet<PhieuChi>();
            this.PhieuChis1 = new HashSet<PhieuChi>();
            this.PhieuNhaps = new HashSet<PhieuNhap>();
            this.PhieuNhaps1 = new HashSet<PhieuNhap>();
            this.PhieuThus = new HashSet<PhieuThu>();
            this.PhieuThus1 = new HashSet<PhieuThu>();
            this.PhieuXuats = new HashSet<PhieuXuat>();
            this.PhieuXuats1 = new HashSet<PhieuXuat>();
        }
    
        public int NhanVienID { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<int> LoaiNhanVienID { get; set; }
        public string TenNhanVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string DiaChi { get; set; }
        public string CMT { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string MoTa { get; set; }
    
        public virtual DMLoaiNhanVien DMLoaiNhanVien { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<HoaDon> HoaDons1 { get; set; }
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
        public virtual ICollection<PhieuChi> PhieuChis { get; set; }
        public virtual ICollection<PhieuChi> PhieuChis1 { get; set; }
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
        public virtual ICollection<PhieuNhap> PhieuNhaps1 { get; set; }
        public virtual ICollection<PhieuThu> PhieuThus { get; set; }
        public virtual ICollection<PhieuThu> PhieuThus1 { get; set; }
        public virtual ICollection<PhieuXuat> PhieuXuats { get; set; }
        public virtual ICollection<PhieuXuat> PhieuXuats1 { get; set; }
    }
}
