//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMNVL
    {
        public DMNVL()
        {
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
            this.ChiTietPhieuXuats = new HashSet<ChiTietPhieuXuat>();
            this.DinhMucs = new HashSet<DinhMuc>();
        }
    
        public int NVLID { get; set; }
        public string MaNVL { get; set; }
        public Nullable<int> LoaiNVLID { get; set; }
        public string TenNVL { get; set; }
        public Nullable<int> DonViTinh { get; set; }
        public Nullable<double> HeSo { get; set; }
        public Nullable<int> DonViTinh1 { get; set; }
        public Nullable<double> HeSo1 { get; set; }
        public Nullable<int> DonViTinh2 { get; set; }
        public Nullable<double> HeSo2 { get; set; }
        public Nullable<int> DonViTinh3 { get; set; }
        public Nullable<double> HeSo3 { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
    
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }
        public virtual ICollection<DinhMuc> DinhMucs { get; set; }
        public virtual DMDonViTinh DMDonViTinh { get; set; }
        public virtual DMDonViTinh DMDonViTinh1 { get; set; }
        public virtual DMDonViTinh DMDonViTinh2 { get; set; }
        public virtual DMDonViTinh DMDonViTinh3 { get; set; }
        public virtual DMLoaiNVL DMLoaiNVL { get; set; }
    }
}
