//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.HoaDon_Ban = new HashSet<HoaDon_Ban>();
        }
    
        public long HoaDonID { get; set; }
        public string MaHoaDon { get; set; }
        public Nullable<long> KhachHangID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> NhanVienBanHang { get; set; }
        public Nullable<double> TongHoaDon { get; set; }
        public Nullable<double> PhuThuTien { get; set; }
        public Nullable<double> PhuThuPhanTram { get; set; }
        public string LyDoPhuThu { get; set; }
        public Nullable<double> PhiPhucVu { get; set; }
        public Nullable<double> PhiPhucVuPhanTram { get; set; }
        public string LyDoPhucVu { get; set; }
        public Nullable<double> GiamGiaThanhVien { get; set; }
        public Nullable<double> KhuyenMaiThanhVien { get; set; }
        public Nullable<double> GiamGiaHoaDon { get; set; }
        public Nullable<double> KhuyenMaiHoaDon { get; set; }
        public Nullable<int> DiemTich { get; set; }
        public Nullable<double> TienConTichDiem { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> DaThanhToan { get; set; }
        public Nullable<double> ChuaThanhToan { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DMKhachHang DMKhachHang { get; set; }
        public virtual DMNhanVien DMNhanVien { get; set; }
        public virtual DMNhanVien DMNhanVien1 { get; set; }
        public virtual ICollection<HoaDon_Ban> HoaDon_Ban { get; set; }
    }
}
