//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassChange
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> datechange { get; set; }
        public string RM { get; set; }
        public string RM1 { get; set; }
        public string RM2 { get; set; }
    }
}
