//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public int CaID { get; set; }
        public int NhanVienID { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> ToiNgay { get; set; }
    
        public virtual DMCa DMCa { get; set; }
        public virtual DMNhanVien DMNhanVien { get; set; }
    }
}
