//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phanQuyen
    {
        public string TenMenu { get; set; }
        public bool VIEW { get; set; }
        public bool ADD { get; set; }
        public bool EDIT { get; set; }
        public bool DELETE { get; set; }
        public bool IMPORT { get; set; }
        public bool EXPORT { get; set; }
        public bool PRINT { get; set; }
        public bool CONTROL { get; set; }
        public string TaiKhoan { get; set; }
    }
}
