//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
    
        public long PhieuNhapID { get; set; }
        public string MaPhieuNhap { get; set; }
        public Nullable<int> LoaiPhieu { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> NguoiNhan { get; set; }
        public Nullable<int> NguoiGiao { get; set; }
        public Nullable<int> ThuKho { get; set; }
        public Nullable<int> NguoiKy { get; set; }
        public string LyDo { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DMLoaiPhieu DMLoaiPhieu { get; set; }
        public virtual DMNhanVien DMNhanVien { get; set; }
        public virtual DMNhanVien DMNhanVien1 { get; set; }
    }
}
