//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNHEntities : DbContext
    {
        public QLNHEntities()
            : base("name=QLNHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<AMenu> AMenus { get; set; }
        public virtual DbSet<ANguoiDung> ANguoiDungs { get; set; }
        public virtual DbSet<ANhatKyHeThong> ANhatKyHeThongs { get; set; }
        public virtual DbSet<ANhomMenu> ANhomMenus { get; set; }
        public virtual DbSet<ANhomNguoiDung> ANhomNguoiDungs { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DbSet<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }
        public virtual DbSet<DinhMuc> DinhMucs { get; set; }
        public virtual DbSet<DMBan> DMBans { get; set; }
        public virtual DbSet<DMCa> DMCas { get; set; }
        public virtual DbSet<DMDonViTinh> DMDonViTinhs { get; set; }
        public virtual DbSet<DMHangHoa> DMHangHoas { get; set; }
        public virtual DbSet<DMKhachHang> DMKhachHangs { get; set; }
        public virtual DbSet<DMLoaiHang> DMLoaiHangs { get; set; }
        public virtual DbSet<DMLoaiKhachHang> DMLoaiKhachHangs { get; set; }
        public virtual DbSet<DMLoaiNhanVien> DMLoaiNhanViens { get; set; }
        public virtual DbSet<DMLoaiNVL> DMLoaiNVLs { get; set; }
        public virtual DbSet<DMLoaiPhieu> DMLoaiPhieux { get; set; }
        public virtual DbSet<DMNhanVien> DMNhanViens { get; set; }
        public virtual DbSet<DMNVL> DMNVLs { get; set; }
        public virtual DbSet<DMPhong> DMPhongs { get; set; }
        public virtual DbSet<DMTang> DMTangs { get; set; }
        public virtual DbSet<GiaBan> GiaBans { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HoaDon_Ban> HoaDon_Ban { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LogError> LogErrors { get; set; }
        public virtual DbSet<PassChange> PassChanges { get; set; }
        public virtual DbSet<PhanCong> PhanCongs { get; set; }
        public virtual DbSet<PhieuChi> PhieuChis { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuThu> PhieuThus { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<RS_Menu> RS_Menu { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<UuDaiThanhVien> UuDaiThanhViens { get; set; }
    }
}
