//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoptype
    {
        public shoptype()
        {
            this.shops = new HashSet<shop>();
        }
    
        public int shoptype_id { get; set; }
        public string name { get; set; }
        public Nullable<int> status_id { get; set; }
    
        public virtual ICollection<shop> shops { get; set; }
        public virtual status status { get; set; }
    }
}
