//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.admins = new HashSet<admin>();
        }
    
        public int status_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<admin> admins { get; set; }
    }
}
