//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.MySonyServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unit", Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    [System.SerializableAttribute()]
    public partial class Unit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ActivatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdapterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlphaNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatteryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpiredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ManufacturingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnitIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarrantyCardNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ActivatedDate {
            get {
                return this.ActivatedDateField;
            }
            set {
                if ((this.ActivatedDateField.Equals(value) != true)) {
                    this.ActivatedDateField = value;
                    this.RaisePropertyChanged("ActivatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdapterNumber {
            get {
                return this.AdapterNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AdapterNumberField, value) != true)) {
                    this.AdapterNumberField = value;
                    this.RaisePropertyChanged("AdapterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlphaNumber {
            get {
                return this.AlphaNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AlphaNumberField, value) != true)) {
                    this.AlphaNumberField = value;
                    this.RaisePropertyChanged("AlphaNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Battery {
            get {
                return this.BatteryField;
            }
            set {
                if ((object.ReferenceEquals(this.BatteryField, value) != true)) {
                    this.BatteryField = value;
                    this.RaisePropertyChanged("Battery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateImport {
            get {
                return this.DateImportField;
            }
            set {
                if ((this.DateImportField.Equals(value) != true)) {
                    this.DateImportField = value;
                    this.RaisePropertyChanged("DateImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiredDate {
            get {
                return this.ExpiredDateField;
            }
            set {
                if ((this.ExpiredDateField.Equals(value) != true)) {
                    this.ExpiredDateField = value;
                    this.RaisePropertyChanged("ExpiredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ManufacturingDate {
            get {
                return this.ManufacturingDateField;
            }
            set {
                if ((this.ManufacturingDateField.Equals(value) != true)) {
                    this.ManufacturingDateField = value;
                    this.RaisePropertyChanged("ManufacturingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartCode {
            get {
                return this.PartCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartCodeField, value) != true)) {
                    this.PartCodeField = value;
                    this.RaisePropertyChanged("PartCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitId {
            get {
                return this.UnitIdField;
            }
            set {
                if ((this.UnitIdField.Equals(value) != true)) {
                    this.UnitIdField = value;
                    this.RaisePropertyChanged("UnitId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarrantyCardNumber {
            get {
                return this.WarrantyCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.WarrantyCardNumberField, value) != true)) {
                    this.WarrantyCardNumberField = value;
                    this.RaisePropertyChanged("WarrantyCardNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegInfo", Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    [System.SerializableAttribute()]
    public partial class RegInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="District", Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    [System.SerializableAttribute()]
    public partial class District : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistrictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistrictId {
            get {
                return this.DistrictIdField;
            }
            set {
                if ((this.DistrictIdField.Equals(value) != true)) {
                    this.DistrictIdField = value;
                    this.RaisePropertyChanged("DistrictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName {
            get {
                return this.DistrictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNameField, value) != true)) {
                    this.DistrictNameField = value;
                    this.RaisePropertyChanged("DistrictName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shop", Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    [System.SerializableAttribute()]
    public partial class Shop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShopIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShopNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShopName {
            get {
                return this.ShopNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopNameField, value) != true)) {
                    this.ShopNameField = value;
                    this.RaisePropertyChanged("ShopName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelId {
            get {
                return this.ModelIdField;
            }
            set {
                if ((this.ModelIdField.Equals(value) != true)) {
                    this.ModelIdField = value;
                    this.RaisePropertyChanged("ModelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MySonyServiceClient.IMySonyService")]
    public interface IMySonyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetUnit", ReplyAction="http://tempuri.org/IMySonyService/GetUnitResponse")]
        MySony.MySonyServiceClient.Unit GetUnit(string modelName, string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetUnit", ReplyAction="http://tempuri.org/IMySonyService/GetUnitResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.Unit> GetUnitAsync(string modelName, string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetMobile", ReplyAction="http://tempuri.org/IMySonyService/GetMobileResponse")]
        MySony.MySonyServiceClient.Unit GetMobile(string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetMobile", ReplyAction="http://tempuri.org/IMySonyService/GetMobileResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.Unit> GetMobileAsync(string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetUnitsBySerial", ReplyAction="http://tempuri.org/IMySonyService/GetUnitsBySerialResponse")]
        MySony.MySonyServiceClient.Unit[] GetUnitsBySerial(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetUnitsBySerial", ReplyAction="http://tempuri.org/IMySonyService/GetUnitsBySerialResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.Unit[]> GetUnitsBySerialAsync(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetUnitForSMS", ReplyAction="http://tempuri.org/IMySonyService/GetUnitForSMSResponse")]
        MySony.MySonyServiceClient.Unit[] GetUnitForSMS(string modelName, string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetUnitForSMS", ReplyAction="http://tempuri.org/IMySonyService/GetUnitForSMSResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.Unit[]> GetUnitForSMSAsync(string modelName, string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetRegInfoForSMS", ReplyAction="http://tempuri.org/IMySonyService/GetRegInfoForSMSResponse")]
        MySony.MySonyServiceClient.RegInfo[] GetRegInfoForSMS(string modelName, string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetRegInfoForSMS", ReplyAction="http://tempuri.org/IMySonyService/GetRegInfoForSMSResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.RegInfo[]> GetRegInfoForSMSAsync(string modelName, string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetAllCity", ReplyAction="http://tempuri.org/IMySonyService/GetAllCityResponse")]
        MySony.MySonyServiceClient.City[] GetAllCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetAllCity", ReplyAction="http://tempuri.org/IMySonyService/GetAllCityResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.City[]> GetAllCityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetDistricts", ReplyAction="http://tempuri.org/IMySonyService/GetDistrictsResponse")]
        MySony.MySonyServiceClient.District[] GetDistricts(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetDistricts", ReplyAction="http://tempuri.org/IMySonyService/GetDistrictsResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.District[]> GetDistrictsAsync(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetShops", ReplyAction="http://tempuri.org/IMySonyService/GetShopsResponse")]
        MySony.MySonyServiceClient.Shop[] GetShops(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetShops", ReplyAction="http://tempuri.org/IMySonyService/GetShopsResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.Shop[]> GetShopsAsync(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetAllCategory", ReplyAction="http://tempuri.org/IMySonyService/GetAllCategoryResponse")]
        MySony.MySonyServiceClient.Category[] GetAllCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetAllCategory", ReplyAction="http://tempuri.org/IMySonyService/GetAllCategoryResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.Category[]> GetAllCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetProducts", ReplyAction="http://tempuri.org/IMySonyService/GetProductsResponse")]
        MySony.MySonyServiceClient.Product[] GetProducts(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySonyService/GetProducts", ReplyAction="http://tempuri.org/IMySonyService/GetProductsResponse")]
        System.Threading.Tasks.Task<MySony.MySonyServiceClient.Product[]> GetProductsAsync(int categoryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMySonyServiceChannel : MySony.MySonyServiceClient.IMySonyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MySonyServiceClient : System.ServiceModel.ClientBase<MySony.MySonyServiceClient.IMySonyService>, MySony.MySonyServiceClient.IMySonyService {
        
        public MySonyServiceClient() {
        }
        
        public MySonyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MySonyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySonyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySonyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MySony.MySonyServiceClient.Unit GetUnit(string modelName, string serialNumber) {
            return base.Channel.GetUnit(modelName, serialNumber);
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.Unit> GetUnitAsync(string modelName, string serialNumber) {
            return base.Channel.GetUnitAsync(modelName, serialNumber);
        }
        
        public MySony.MySonyServiceClient.Unit GetMobile(string imei) {
            return base.Channel.GetMobile(imei);
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.Unit> GetMobileAsync(string imei) {
            return base.Channel.GetMobileAsync(imei);
        }
        
        public MySony.MySonyServiceClient.Unit[] GetUnitsBySerial(string serialNumber) {
            return base.Channel.GetUnitsBySerial(serialNumber);
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.Unit[]> GetUnitsBySerialAsync(string serialNumber) {
            return base.Channel.GetUnitsBySerialAsync(serialNumber);
        }
        
        public MySony.MySonyServiceClient.Unit[] GetUnitForSMS(string modelName, string serialNumber) {
            return base.Channel.GetUnitForSMS(modelName, serialNumber);
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.Unit[]> GetUnitForSMSAsync(string modelName, string serialNumber) {
            return base.Channel.GetUnitForSMSAsync(modelName, serialNumber);
        }
        
        public MySony.MySonyServiceClient.RegInfo[] GetRegInfoForSMS(string modelName, string serialNumber) {
            return base.Channel.GetRegInfoForSMS(modelName, serialNumber);
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.RegInfo[]> GetRegInfoForSMSAsync(string modelName, string serialNumber) {
            return base.Channel.GetRegInfoForSMSAsync(modelName, serialNumber);
        }
        
        public MySony.MySonyServiceClient.City[] GetAllCity() {
            return base.Channel.GetAllCity();
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.City[]> GetAllCityAsync() {
            return base.Channel.GetAllCityAsync();
        }
        
        public MySony.MySonyServiceClient.District[] GetDistricts(int cityId) {
            return base.Channel.GetDistricts(cityId);
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.District[]> GetDistrictsAsync(int cityId) {
            return base.Channel.GetDistrictsAsync(cityId);
        }
        
        public MySony.MySonyServiceClient.Shop[] GetShops(int cityId) {
            return base.Channel.GetShops(cityId);
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.Shop[]> GetShopsAsync(int cityId) {
            return base.Channel.GetShopsAsync(cityId);
        }
        
        public MySony.MySonyServiceClient.Category[] GetAllCategory() {
            return base.Channel.GetAllCategory();
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.Category[]> GetAllCategoryAsync() {
            return base.Channel.GetAllCategoryAsync();
        }
        
        public MySony.MySonyServiceClient.Product[] GetProducts(int categoryId) {
            return base.Channel.GetProducts(categoryId);
        }
        
        public System.Threading.Tasks.Task<MySony.MySonyServiceClient.Product[]> GetProductsAsync(int categoryId) {
            return base.Channel.GetProductsAsync(categoryId);
        }
    }
}
