//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace MySony.vn.com.sony.mysony {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'EndpointReference' from namespace 'http://www.w3.org/2005/08/addressing' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSHttpBinding_IMySonyService", Namespace="http://tempuri.org/")]
    public partial class MySonyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMobileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnitsBySerialOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnitForSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegInfoForSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDistrictsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShopsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MySonyService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::MySony.Properties.Settings.Default.MySony_vn_com_sony_mysony_MySonyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUnitCompletedEventHandler GetUnitCompleted;
        
        /// <remarks/>
        public event GetMobileCompletedEventHandler GetMobileCompleted;
        
        /// <remarks/>
        public event GetUnitsBySerialCompletedEventHandler GetUnitsBySerialCompleted;
        
        /// <remarks/>
        public event GetUnitForSMSCompletedEventHandler GetUnitForSMSCompleted;
        
        /// <remarks/>
        public event GetRegInfoForSMSCompletedEventHandler GetRegInfoForSMSCompleted;
        
        /// <remarks/>
        public event GetAllCityCompletedEventHandler GetAllCityCompleted;
        
        /// <remarks/>
        public event GetDistrictsCompletedEventHandler GetDistrictsCompleted;
        
        /// <remarks/>
        public event GetShopsCompletedEventHandler GetShopsCompleted;
        
        /// <remarks/>
        public event GetAllCategoryCompletedEventHandler GetAllCategoryCompleted;
        
        /// <remarks/>
        public event GetProductsCompletedEventHandler GetProductsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Unit GetUnit([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string modelName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serialNumber) {
            object[] results = this.Invoke("GetUnit", new object[] {
                        modelName,
                        serialNumber});
            return ((Unit)(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitAsync(string modelName, string serialNumber) {
            this.GetUnitAsync(modelName, serialNumber, null);
        }
        
        /// <remarks/>
        public void GetUnitAsync(string modelName, string serialNumber, object userState) {
            if ((this.GetUnitOperationCompleted == null)) {
                this.GetUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitOperationCompleted);
            }
            this.InvokeAsync("GetUnit", new object[] {
                        modelName,
                        serialNumber}, this.GetUnitOperationCompleted, userState);
        }
        
        private void OnGetUnitOperationCompleted(object arg) {
            if ((this.GetUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitCompleted(this, new GetUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Unit GetMobile([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string imei) {
            object[] results = this.Invoke("GetMobile", new object[] {
                        imei});
            return ((Unit)(results[0]));
        }
        
        /// <remarks/>
        public void GetMobileAsync(string imei) {
            this.GetMobileAsync(imei, null);
        }
        
        /// <remarks/>
        public void GetMobileAsync(string imei, object userState) {
            if ((this.GetMobileOperationCompleted == null)) {
                this.GetMobileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMobileOperationCompleted);
            }
            this.InvokeAsync("GetMobile", new object[] {
                        imei}, this.GetMobileOperationCompleted, userState);
        }
        
        private void OnGetMobileOperationCompleted(object arg) {
            if ((this.GetMobileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMobileCompleted(this, new GetMobileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetUnitsBySerial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
        public Unit[] GetUnitsBySerial([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serialNumber) {
            object[] results = this.Invoke("GetUnitsBySerial", new object[] {
                        serialNumber});
            return ((Unit[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitsBySerialAsync(string serialNumber) {
            this.GetUnitsBySerialAsync(serialNumber, null);
        }
        
        /// <remarks/>
        public void GetUnitsBySerialAsync(string serialNumber, object userState) {
            if ((this.GetUnitsBySerialOperationCompleted == null)) {
                this.GetUnitsBySerialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitsBySerialOperationCompleted);
            }
            this.InvokeAsync("GetUnitsBySerial", new object[] {
                        serialNumber}, this.GetUnitsBySerialOperationCompleted, userState);
        }
        
        private void OnGetUnitsBySerialOperationCompleted(object arg) {
            if ((this.GetUnitsBySerialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitsBySerialCompleted(this, new GetUnitsBySerialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetUnitForSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
        public Unit[] GetUnitForSMS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string modelName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serialNumber) {
            object[] results = this.Invoke("GetUnitForSMS", new object[] {
                        modelName,
                        serialNumber});
            return ((Unit[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitForSMSAsync(string modelName, string serialNumber) {
            this.GetUnitForSMSAsync(modelName, serialNumber, null);
        }
        
        /// <remarks/>
        public void GetUnitForSMSAsync(string modelName, string serialNumber, object userState) {
            if ((this.GetUnitForSMSOperationCompleted == null)) {
                this.GetUnitForSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitForSMSOperationCompleted);
            }
            this.InvokeAsync("GetUnitForSMS", new object[] {
                        modelName,
                        serialNumber}, this.GetUnitForSMSOperationCompleted, userState);
        }
        
        private void OnGetUnitForSMSOperationCompleted(object arg) {
            if ((this.GetUnitForSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitForSMSCompleted(this, new GetUnitForSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetRegInfoForSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
        public RegInfo[] GetRegInfoForSMS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string modelName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serialNumber) {
            object[] results = this.Invoke("GetRegInfoForSMS", new object[] {
                        modelName,
                        serialNumber});
            return ((RegInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegInfoForSMSAsync(string modelName, string serialNumber) {
            this.GetRegInfoForSMSAsync(modelName, serialNumber, null);
        }
        
        /// <remarks/>
        public void GetRegInfoForSMSAsync(string modelName, string serialNumber, object userState) {
            if ((this.GetRegInfoForSMSOperationCompleted == null)) {
                this.GetRegInfoForSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegInfoForSMSOperationCompleted);
            }
            this.InvokeAsync("GetRegInfoForSMS", new object[] {
                        modelName,
                        serialNumber}, this.GetRegInfoForSMSOperationCompleted, userState);
        }
        
        private void OnGetRegInfoForSMSOperationCompleted(object arg) {
            if ((this.GetRegInfoForSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegInfoForSMSCompleted(this, new GetRegInfoForSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetAllCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
        public City[] GetAllCity() {
            object[] results = this.Invoke("GetAllCity", new object[0]);
            return ((City[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCityAsync() {
            this.GetAllCityAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCityAsync(object userState) {
            if ((this.GetAllCityOperationCompleted == null)) {
                this.GetAllCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCityOperationCompleted);
            }
            this.InvokeAsync("GetAllCity", new object[0], this.GetAllCityOperationCompleted, userState);
        }
        
        private void OnGetAllCityOperationCompleted(object arg) {
            if ((this.GetAllCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCityCompleted(this, new GetAllCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetDistricts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
        public District[] GetDistricts(int cityId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cityIdSpecified) {
            object[] results = this.Invoke("GetDistricts", new object[] {
                        cityId,
                        cityIdSpecified});
            return ((District[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDistrictsAsync(int cityId, bool cityIdSpecified) {
            this.GetDistrictsAsync(cityId, cityIdSpecified, null);
        }
        
        /// <remarks/>
        public void GetDistrictsAsync(int cityId, bool cityIdSpecified, object userState) {
            if ((this.GetDistrictsOperationCompleted == null)) {
                this.GetDistrictsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDistrictsOperationCompleted);
            }
            this.InvokeAsync("GetDistricts", new object[] {
                        cityId,
                        cityIdSpecified}, this.GetDistrictsOperationCompleted, userState);
        }
        
        private void OnGetDistrictsOperationCompleted(object arg) {
            if ((this.GetDistrictsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDistrictsCompleted(this, new GetDistrictsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetShops", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
        public Shop[] GetShops(int cityId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cityIdSpecified) {
            object[] results = this.Invoke("GetShops", new object[] {
                        cityId,
                        cityIdSpecified});
            return ((Shop[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShopsAsync(int cityId, bool cityIdSpecified) {
            this.GetShopsAsync(cityId, cityIdSpecified, null);
        }
        
        /// <remarks/>
        public void GetShopsAsync(int cityId, bool cityIdSpecified, object userState) {
            if ((this.GetShopsOperationCompleted == null)) {
                this.GetShopsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShopsOperationCompleted);
            }
            this.InvokeAsync("GetShops", new object[] {
                        cityId,
                        cityIdSpecified}, this.GetShopsOperationCompleted, userState);
        }
        
        private void OnGetShopsOperationCompleted(object arg) {
            if ((this.GetShopsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShopsCompleted(this, new GetShopsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetAllCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
        public Category[] GetAllCategory() {
            object[] results = this.Invoke("GetAllCategory", new object[0]);
            return ((Category[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCategoryAsync() {
            this.GetAllCategoryAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCategoryAsync(object userState) {
            if ((this.GetAllCategoryOperationCompleted == null)) {
                this.GetAllCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCategoryOperationCompleted);
            }
            this.InvokeAsync("GetAllCategory", new object[0], this.GetAllCategoryOperationCompleted, userState);
        }
        
        private void OnGetAllCategoryOperationCompleted(object arg) {
            if ((this.GetAllCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCategoryCompleted(this, new GetAllCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMySonyService/GetProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
        public Product[] GetProducts(int categoryId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool categoryIdSpecified) {
            object[] results = this.Invoke("GetProducts", new object[] {
                        categoryId,
                        categoryIdSpecified});
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsAsync(int categoryId, bool categoryIdSpecified) {
            this.GetProductsAsync(categoryId, categoryIdSpecified, null);
        }
        
        /// <remarks/>
        public void GetProductsAsync(int categoryId, bool categoryIdSpecified, object userState) {
            if ((this.GetProductsOperationCompleted == null)) {
                this.GetProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsOperationCompleted);
            }
            this.InvokeAsync("GetProducts", new object[] {
                        categoryId,
                        categoryIdSpecified}, this.GetProductsOperationCompleted, userState);
        }
        
        private void OnGetProductsOperationCompleted(object arg) {
            if ((this.GetProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsCompleted(this, new GetProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    public partial class Unit {
        
        private System.Nullable<System.DateTime> activatedDateField;
        
        private bool activatedDateFieldSpecified;
        
        private string adapterNumberField;
        
        private string alphaNumberField;
        
        private string batteryField;
        
        private System.Nullable<System.DateTime> dateImportField;
        
        private bool dateImportFieldSpecified;
        
        private System.Nullable<System.DateTime> expiredDateField;
        
        private bool expiredDateFieldSpecified;
        
        private System.Nullable<System.DateTime> manufacturingDateField;
        
        private bool manufacturingDateFieldSpecified;
        
        private string modelNameField;
        
        private string partCodeField;
        
        private System.Nullable<decimal> periodField;
        
        private bool periodFieldSpecified;
        
        private string productCodeField;
        
        private string serialNumberField;
        
        private string statusField;
        
        private int unitIdField;
        
        private bool unitIdFieldSpecified;
        
        private string warrantyCardNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ActivatedDate {
            get {
                return this.activatedDateField;
            }
            set {
                this.activatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActivatedDateSpecified {
            get {
                return this.activatedDateFieldSpecified;
            }
            set {
                this.activatedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdapterNumber {
            get {
                return this.adapterNumberField;
            }
            set {
                this.adapterNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AlphaNumber {
            get {
                return this.alphaNumberField;
            }
            set {
                this.alphaNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Battery {
            get {
                return this.batteryField;
            }
            set {
                this.batteryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateImport {
            get {
                return this.dateImportField;
            }
            set {
                this.dateImportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateImportSpecified {
            get {
                return this.dateImportFieldSpecified;
            }
            set {
                this.dateImportFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpiredDate {
            get {
                return this.expiredDateField;
            }
            set {
                this.expiredDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiredDateSpecified {
            get {
                return this.expiredDateFieldSpecified;
            }
            set {
                this.expiredDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ManufacturingDate {
            get {
                return this.manufacturingDateField;
            }
            set {
                this.manufacturingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ManufacturingDateSpecified {
            get {
                return this.manufacturingDateFieldSpecified;
            }
            set {
                this.manufacturingDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PartCode {
            get {
                return this.partCodeField;
            }
            set {
                this.partCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeriodSpecified {
            get {
                return this.periodFieldSpecified;
            }
            set {
                this.periodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitIdSpecified {
            get {
                return this.unitIdFieldSpecified;
            }
            set {
                this.unitIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WarrantyCardNumber {
            get {
                return this.warrantyCardNumberField;
            }
            set {
                this.warrantyCardNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    public partial class Product {
        
        private int modelIdField;
        
        private bool modelIdFieldSpecified;
        
        private string modelNameField;
        
        /// <remarks/>
        public int ModelId {
            get {
                return this.modelIdField;
            }
            set {
                this.modelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModelIdSpecified {
            get {
                return this.modelIdFieldSpecified;
            }
            set {
                this.modelIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    public partial class Category {
        
        private int categoryIdField;
        
        private bool categoryIdFieldSpecified;
        
        private string categoryNameField;
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoryIdSpecified {
            get {
                return this.categoryIdFieldSpecified;
            }
            set {
                this.categoryIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    public partial class Shop {
        
        private int shopIdField;
        
        private bool shopIdFieldSpecified;
        
        private string shopNameField;
        
        /// <remarks/>
        public int ShopId {
            get {
                return this.shopIdField;
            }
            set {
                this.shopIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShopIdSpecified {
            get {
                return this.shopIdFieldSpecified;
            }
            set {
                this.shopIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShopName {
            get {
                return this.shopNameField;
            }
            set {
                this.shopNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    public partial class District {
        
        private int districtIdField;
        
        private bool districtIdFieldSpecified;
        
        private string districtNameField;
        
        /// <remarks/>
        public int DistrictId {
            get {
                return this.districtIdField;
            }
            set {
                this.districtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistrictIdSpecified {
            get {
                return this.districtIdFieldSpecified;
            }
            set {
                this.districtIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    public partial class City {
        
        private int cityIdField;
        
        private bool cityIdFieldSpecified;
        
        private string cityNameField;
        
        /// <remarks/>
        public int CityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CityIdSpecified {
            get {
                return this.cityIdFieldSpecified;
            }
            set {
                this.cityIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MySonyService.Constracts")]
    public partial class RegInfo {
        
        private string cardNumberField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string homePhoneField;
        
        private string lastNameField;
        
        private string mobilePhoneField;
        
        private string modelNameField;
        
        private System.Nullable<System.DateTime> regDateField;
        
        private bool regDateFieldSpecified;
        
        private string serialNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> RegDate {
            get {
                return this.regDateField;
            }
            set {
                this.regDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegDateSpecified {
            get {
                return this.regDateFieldSpecified;
            }
            set {
                this.regDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUnitCompletedEventHandler(object sender, GetUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Unit Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Unit)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMobileCompletedEventHandler(object sender, GetMobileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMobileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMobileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Unit Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Unit)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUnitsBySerialCompletedEventHandler(object sender, GetUnitsBySerialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitsBySerialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitsBySerialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Unit[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Unit[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUnitForSMSCompletedEventHandler(object sender, GetUnitForSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitForSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitForSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Unit[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Unit[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRegInfoForSMSCompletedEventHandler(object sender, GetRegInfoForSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegInfoForSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegInfoForSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RegInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RegInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllCityCompletedEventHandler(object sender, GetAllCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public City[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((City[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetDistrictsCompletedEventHandler(object sender, GetDistrictsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDistrictsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDistrictsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public District[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((District[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetShopsCompletedEventHandler(object sender, GetShopsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShopsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShopsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Shop[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Shop[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllCategoryCompletedEventHandler(object sender, GetAllCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Category[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Category[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetProductsCompletedEventHandler(object sender, GetProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591