//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public admin()
        {
            this.RS_Category = new HashSet<RS_Category>();
            this.RS_Category1 = new HashSet<RS_Category>();
            this.RS_FAQ = new HashSet<RS_FAQ>();
            this.RS_FAQ1 = new HashSet<RS_FAQ>();
            this.RS_Menu = new HashSet<RS_Menu>();
            this.RS_Menu1 = new HashSet<RS_Menu>();
            this.RS_Video = new HashSet<RS_Video>();
            this.RS_Video1 = new HashSet<RS_Video>();
        }
    
        public int admin_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> admin_type { get; set; }
        public Nullable<int> status_id { get; set; }
        public string admincodereg { get; set; }
    
        public virtual status status { get; set; }
        public virtual ICollection<RS_Category> RS_Category { get; set; }
        public virtual ICollection<RS_Category> RS_Category1 { get; set; }
        public virtual ICollection<RS_FAQ> RS_FAQ { get; set; }
        public virtual ICollection<RS_FAQ> RS_FAQ1 { get; set; }
        public virtual ICollection<RS_Menu> RS_Menu { get; set; }
        public virtual ICollection<RS_Menu> RS_Menu1 { get; set; }
        public virtual ICollection<RS_Video> RS_Video { get; set; }
        public virtual ICollection<RS_Video> RS_Video1 { get; set; }
    }
}
