//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANguoiDung
    {
        public int NguoiDungID { get; set; }
        public string MaNguoiDung { get; set; }
        public string MaNhomNguoiDung { get; set; }
        public string MatKhau { get; set; }
        public string TaiKhoan { get; set; }
        public bool TrangThai { get; set; }
        public string MoTa { get; set; }
        public string MaNhanVien { get; set; }
        public string NguoiDung { get; set; }
        public string ChucNang { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ANhomNguoiDung ANhomNguoiDung { get; set; }
    }
}
