//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANhomMenu
    {
        public int NhomMenuID { get; set; }
        public string MaMenu { get; set; }
        public string MaNhomNguoiDung { get; set; }
        public bool VIEW { get; set; }
        public bool ADD { get; set; }
        public bool EDIT { get; set; }
        public bool DELETE { get; set; }
        public bool IMPORT { get; set; }
        public bool EXPORT { get; set; }
        public bool PRINT { get; set; }
        public bool CONTROL { get; set; }
        public string NguoiDung { get; set; }
        public string ChucNang { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual AMenu AMenu { get; set; }
        public virtual ANhomNguoiDung ANhomNguoiDung { get; set; }
    }
}
