//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.orders = new HashSet<order>();
            this.products = new HashSet<product>();
        }
    
        public int category_id { get; set; }
        public string name { get; set; }
        public string modelImage { get; set; }
        public string serialImage { get; set; }
        public string nameImage { get; set; }
        public Nullable<int> status_id { get; set; }
        public string viewModelImage { get; set; }
        public string viewSerialImage { get; set; }
        public Nullable<int> RS_base_warranty_months { get; set; }
    
        public virtual status status { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
