//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public long HoaDonID { get; set; }
        public long HangHoaID { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DMHangHoa DMHangHoa { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
