//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public city()
        {
            this.districts = new HashSet<district>();
            this.RS_Branch = new HashSet<RS_Branch>();
            this.shops = new HashSet<shop>();
            this.customers = new HashSet<customer>();
        }
    
        public int city_id { get; set; }
        public string name { get; set; }
        public Nullable<int> porder { get; set; }
        public Nullable<int> status_id { get; set; }
    
        public virtual status status { get; set; }
        public virtual ICollection<district> districts { get; set; }
        public virtual ICollection<RS_Branch> RS_Branch { get; set; }
        public virtual ICollection<shop> shops { get; set; }
        public virtual ICollection<customer> customers { get; set; }
    }
}
