//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMHangHoa
    {
        public DMHangHoa()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.DinhMucs = new HashSet<DinhMuc>();
            this.GiaBans = new HashSet<GiaBan>();
        }
    
        public long HangHoaID { get; set; }
        public Nullable<int> LoaiHangID { get; set; }
        public string MaHangHoa { get; set; }
        public string TenHangHoa { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual ICollection<DinhMuc> DinhMucs { get; set; }
        public virtual DMLoaiHang DMLoaiHang { get; set; }
        public virtual ICollection<GiaBan> GiaBans { get; set; }
    }
}
