//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMLoaiPhieu
    {
        public DMLoaiPhieu()
        {
            this.PhieuChis = new HashSet<PhieuChi>();
            this.PhieuNhaps = new HashSet<PhieuNhap>();
            this.PhieuThus = new HashSet<PhieuThu>();
            this.PhieuXuats = new HashSet<PhieuXuat>();
        }
    
        public int LoaiPhieuID { get; set; }
        public string MaLoaiPhieu { get; set; }
        public string TenLoaiPhieu { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<PhieuChi> PhieuChis { get; set; }
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
        public virtual ICollection<PhieuThu> PhieuThus { get; set; }
        public virtual ICollection<PhieuXuat> PhieuXuats { get; set; }
    }
}
