//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMLoaiKhachHang
    {
        public DMLoaiKhachHang()
        {
            this.DMKhachHangs = new HashSet<DMKhachHang>();
            this.UuDaiThanhViens = new HashSet<UuDaiThanhVien>();
        }
    
        public int LoaiKhachHangID { get; set; }
        public string MaLoaiKhachHang { get; set; }
        public string TenLoaiKhachHang { get; set; }
    
        public virtual ICollection<DMKhachHang> DMKhachHangs { get; set; }
        public virtual ICollection<UuDaiThanhVien> UuDaiThanhViens { get; set; }
    }
}
