//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaBan
    {
        public int GiaBanID { get; set; }
        public Nullable<long> HangHoaID { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<double> KhuyenMai { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public string MoTa { get; set; }
    
        public virtual DMHangHoa DMHangHoa { get; set; }
    }
}
