//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon_Ban
    {
        public int STT { get; set; }
        public Nullable<long> HoaDonID { get; set; }
        public Nullable<int> BanID { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual DMBan DMBan { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
