//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public Nullable<int> catagory_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string serial { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> shop_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public string cardnumber { get; set; }
        public Nullable<System.DateTime> smssentdate { get; set; }
        public string RM { get; set; }
        public string RM1 { get; set; }
        public string RM2 { get; set; }
        public Nullable<System.DateTime> WarrantyStart { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> WarrantyEnd { get; set; }
    
        public virtual category category { get; set; }
        public virtual city city { get; set; }
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
        public virtual shop shop { get; set; }
        public virtual status status { get; set; }
    }
}
