//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public PhieuXuat()
        {
            this.ChiTietPhieuXuats = new HashSet<ChiTietPhieuXuat>();
        }
    
        public long PhieuXuatID { get; set; }
        public string MaPhieuXuat { get; set; }
        public Nullable<int> LoaiPhieuID { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<long> NguoiNhan { get; set; }
        public Nullable<int> NguoiGiao { get; set; }
        public Nullable<int> ThuKho { get; set; }
        public Nullable<int> NguoiKy { get; set; }
        public string LyDo { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }
        public virtual DMLoaiPhieu DMLoaiPhieu { get; set; }
        public virtual DMNhanVien DMNhanVien { get; set; }
        public virtual DMNhanVien DMNhanVien1 { get; set; }
    }
}
