//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChi
    {
        public long PhieuChiID { get; set; }
        public string SoPhieu { get; set; }
        public string SoPhieuLienQuan { get; set; }
        public Nullable<int> LoaiPhieu { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> IsHDTC { get; set; }
        public string SoHD { get; set; }
        public string LyDo { get; set; }
        public string SoQui { get; set; }
        public Nullable<double> TyGia { get; set; }
        public Nullable<double> QuyDoi { get; set; }
        public Nullable<int> NguoiChi { get; set; }
        public Nullable<int> NguoiLapPhieu { get; set; }
        public Nullable<long> KhachHang { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DMKhachHang DMKhachHang { get; set; }
        public virtual DMLoaiPhieu DMLoaiPhieu { get; set; }
        public virtual DMNhanVien DMNhanVien { get; set; }
        public virtual DMNhanVien DMNhanVien1 { get; set; }
    }
}
