//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.orders = new HashSet<order>();
        }
    
        public int product_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string productcode { get; set; }
        public string name { get; set; }
        public Nullable<int> status_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual status status { get; set; }
    }
}
