//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resethistory
    {
        public int para_id { get; set; }
        public string customercodereg { get; set; }
        public Nullable<System.DateTime> senttime { get; set; }
        public Nullable<System.DateTime> expiredtime { get; set; }
        public string longsenttime { get; set; }
        public Nullable<int> status_id { get; set; }
    }
}
