//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Article
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Title { get; set; }
        public string Thumbnail { get; set; }
        public string Brief { get; set; }
        public string ArticleContent { get; set; }
        public string Slug { get; set; }
        public bool IsTop { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string PublishDate { get; set; }
        public Nullable<int> OrderNo { get; set; }
    
        public virtual RS_Category RS_Category { get; set; }
        public virtual RS_Category RS_Category1 { get; set; }
    }
}
