//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Branch
    {
        public RS_Branch()
        {
            this.shops = new HashSet<shop>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public int city_id { get; set; }
        public int status_id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual city city { get; set; }
        public virtual status status { get; set; }
        public virtual ICollection<shop> shops { get; set; }
    }
}
