//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Config
    {
        public int ID { get; set; }
        public string BannerHome { get; set; }
        public string BackgroundLanding { get; set; }
        public string LandingContent { get; set; }
    }
}
