//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Category
    {
        public RS_Category()
        {
            this.RS_Article = new HashSet<RS_Article>();
            this.RS_Article1 = new HashSet<RS_Article>();
            this.RS_Images = new HashSet<RS_Images>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Tags { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual admin admin1 { get; set; }
        public virtual ICollection<RS_Article> RS_Article { get; set; }
        public virtual ICollection<RS_Article> RS_Article1 { get; set; }
        public virtual ICollection<RS_Images> RS_Images { get; set; }
    }
}
