//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Video
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Brief { get; set; }
        public string Descript { get; set; }
        public string Thumb { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public int Status { get; set; }
        public bool IsHighlight { get; set; }
        public string PublishDate { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual admin admin1 { get; set; }
    }
}
