//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop
    {
        public shop()
        {
            this.orders = new HashSet<order>();
        }
    
        public int shop_id { get; set; }
        public string name { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> shoptype_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> order_no { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual RS_Branch RS_Branch { get; set; }
        public virtual shoptype shoptype { get; set; }
        public virtual status status { get; set; }
    }
}
