//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.admins = new HashSet<admin>();
            this.categories = new HashSet<category>();
            this.cities = new HashSet<city>();
            this.customers = new HashSet<customer>();
            this.customertypes = new HashSet<customertype>();
            this.districts = new HashSet<district>();
            this.educations = new HashSet<education>();
            this.jobs = new HashSet<job>();
            this.orders = new HashSet<order>();
            this.products = new HashSet<product>();
            this.RS_Branch = new HashSet<RS_Branch>();
            this.RS_mail_template = new HashSet<RS_mail_template>();
            this.serials = new HashSet<serial>();
            this.shops = new HashSet<shop>();
            this.shoptypes = new HashSet<shoptype>();
        }
    
        public int status_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<admin> admins { get; set; }
        public virtual ICollection<category> categories { get; set; }
        public virtual ICollection<city> cities { get; set; }
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<customertype> customertypes { get; set; }
        public virtual ICollection<district> districts { get; set; }
        public virtual ICollection<education> educations { get; set; }
        public virtual ICollection<job> jobs { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<RS_Branch> RS_Branch { get; set; }
        public virtual ICollection<RS_mail_template> RS_mail_template { get; set; }
        public virtual ICollection<serial> serials { get; set; }
        public virtual ICollection<shop> shops { get; set; }
        public virtual ICollection<shoptype> shoptypes { get; set; }
    }
}
